sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
  - $HOME/.pip-cache
dist: trusty
language: python


matrix:
  include:
  - python: '3.6'
    env: TOXENV="py27-linux"

  - python: '3.8'
    env: TOXENV="py36-linux"

  - python: '3.8'
    env: TOXENV="check"

install: pip install tox
script: tox -vv
